// responsible for access to db
//will be used in BookService

package com.example.demo.book;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.stereotype.Repository;
import java.util.Optional;

@Repository
public interface BookRepository // from JpaRepository receives .findAll()
        extends JpaRepository<Book, Long> { // type of object we want to work this repository with/datatype of id
    // + why do we need datatype of id if we know the class (Book) to find objects?
    // custom function to find book by title
    // @Query("SELECT book FROM Book book WHERE book.title = ?1") // + JBQL - looks for Book object with passed title, + what does ?1 mean? a placeholder?
    // + is this method generated by JPA repo findBooksByTitle(String title)???
    Optional<Book> findBooksByTitle(String title); // Optional is intended to be used as a method return type where there is a clear need to represent "no result," and where using null is likely to cause errors.
} // + why findBooksByTitle(String title) method is exactly here, not for ex in book service?
